name: notify-slack
description: Sends a message to slack
inputs:
  message:
    description: The message to send
    required: true
  slack_webhook_url:
    description: The Slack's webhook url
    required: true
  type:
    description: The message type (good, warning, danger)
    required: false
    default: good
outputs:
  sent_message:
    description: The date with message sent
runs:
  using: node20
  main: main.js
